### ISSUE TITLE
-arch option unavailable on Linux systems

### ISSUE THREAD

**Issue by joshuacrotts** [IUCompilerCourse/public-student-support-code#28]
The patch from using the `-march` flag to `-arch` in commit [d732589](https://github.com/IUCompilerCourse/public-student-support-code/commit/d7325890018f0771103aa9ed37c91b0ad31a59a1) breaks compilation on Linux systems since `-arch` is only supported by Clang. 

To fix, we can add a binding to `compiler-tests-suite` that removes the flag for non-MacOS ARM-based systems.

```Racket
(let ([gcc-cmd (if (and (equal? (system-type 'os) 'macosx)
                        (equal? (system-type 'arch) 'aarch64))
                   "gcc -g -std=c99 -arch x86_64"
                   "gcc -g -std=c99")])
  (let ([gcc-output (system (format "~a runtime.o ./tests/~a.s -o ./tests/~a.out" gcc-cmd test-name test-name))])
    ...
```

**Comment by jsiek** [comment]
fixed, thanks!
