### ISSUE TITLE
[Request] LICENSE for repository code

### ISSUE THREAD

**Issue by sidkshatriya** [IUCompilerCourse/public-student-support-code#7]
I was wondering if we can have a LICENSE to the code in this repository. 

It would clarify the expectations about what can be done with this code. Moreover, people can consider other interesting projects e.g. translation to other computer languages and so on.

It would be great to provide a LICENSE to the Essentials of Compilation book too. Again, it would clarify expectations on what is permitted.

**Comment by jsiek** [comment]
I've chosen the MIT license for this support code.

Not sure yet about the book.
